name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dist
        run: |
          rm -rf dist
          mkdir -p dist
          shopt -s dotglob
          cp -R * dist/
          # ensure node_modules or tooling folders (if any) are not copied
          rm -rf dist/node_modules || true

      - name: Inject Google API key meta (if provided)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          # Insert meta tag before </head> in index.html, only if secret is set
          if [ -n "${GOOGLE_API_KEY}" ]; then
            sed -i 's#</head>#  <meta name="google-api-key" content="'"${GOOGLE_API_KEY}"'"/>\n</head>#' dist/index.html
            echo "Injected google-api-key meta"
          else
            echo "GOOGLE_API_KEY not set; skipping injection"
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          force_orphan: true
